services:
  - type: web
    name: messenger-bot
    env: node
    region: oregon # يمكنك تغيير المنطقة حسب موقعك
    buildCommand: npm install
    startCommand: node index.js # قم بتعديل "index.js" إذا كان الملف الرئيسي مختلفًا
    plan: free # اختر الخطة التي تناسبك
